# Generated by Django 4.1.3 on 2022-12-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("intro", models.TextField()),
                ("date", models.DateField()),
                ("link", models.URLField()),
                ("image", models.CharField(default="pythonimg.png", max_length=255)),
            ],
        ),
    ]
